name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: emilgruzalski/gh-actions/.github/workflows/ci-img-go.yml@v1
    with:
      image-name: 'zguba-gov'
      push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    permissions:
      contents: write
      packages: write